set hyperbase.reader=true;
SELECT SUB.FASSETBALPART,
       COUNT(*) AS CUSTNUM
  FROM          
    HYPERBASE_FIN_CUST_INFO_BASE BASE
  INNER JOIN
    HYPERBASE_FIN_CUST_INFO_SUB SUB
  ON SUB.rk.CUSTNO = BASE.rk.CUSTNO
  WHERE BASE.CUSTTYPE='0'
  GROUP BY SUB.FASSETBALPART
  ORDER BY CUSTNUM;
