drop table hyperbase_FIN_LEADOPPS;
CREATE EXTERNAL TABLE hyperbase_FIN_LEADOPPS (
  rk struct<CUSTNO:STRING>,
  RECCREATEDATE STRING,
  CLTID STRING,
  LEADOPPPHASE STRING,
  USERID STRING,
  ORGID STRING,
  RECCREATEUID STRING
)
ROW FORMAT DELIMITED
COLLECTION ITEMS TERMINATED BY '~'
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES (
"hbase.columns.mapping" = ":key,f1:RECCREATEDATE,f:CLTID,f:LEADOPPPHASE,f:USERID,f:ORGID,f:RECCREATEUID"
)TBLPROPERTIES ("hbase.table.name" = "FIN_LEADOPPS");
