DROP TABLE IF EXISTS sample_FIN_LEADOPPS;
CREATE EXTERNAL TABLE sample_FIN_LEADOPPS (
		  time string,
		  allvalue string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/import_data/sadata/FIN_LEADOPPS';
