DROP TABLE IF EXISTS sample_FIN_CUST_FMANAGER;
CREATE EXTERNAL TABLE sample_FIN_CUST_FMANAGER (
		  allvalue string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/import_data/sadata/FIN_CUST_FMANAGER';
