drop table hyperbase_FIN_CONFINPROFILE_BASE;
CREATE EXTERNAL TABLE hyperbase_FIN_CONFINPROFILE_BASE (
  rk struct<CUSTNO:STRING>,
  DEPOSITBALAVGL3M STRING,
  FASSETBAL STRING,
  FASSETBALMAX STRING,
  FASSETBALAVGMMAX STRING
)
ROW FORMAT DELIMITED
COLLECTION ITEMS TERMINATED BY '~'
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES (
"hbase.columns.mapping" = ":key,f1:DEPOSITBALAVGL3M,f1:FASSETBAL,f1:FASSETBALMAX,f1:FASSETBALAVGMMAX"
)TBLPROPERTIES ("hbase.table.name" = "FIN_CONFINPROFILE_BASE");
