DROP TABLE IF EXISTS sample_FIN_CONFINPROFILE_BASE;
CREATE EXTERNAL TABLE sample_FIN_CONFINPROFILE_BASE (
		  allvalue string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/import_data/sadata/FIN_CONFINPROFILE_BASE';
