DROP TABLE IF EXISTS sample_FIN_CAMPLEADTEM;
CREATE EXTERNAL TABLE sample_FIN_CAMPLEADTEM (
		  allvalue string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/import_data/sadata/FIN_CAMPLEADTEM';
