DROP TABLE IF EXISTS sample_FIN_CUST_CMANAGER;
CREATE EXTERNAL TABLE sample_FIN_CUST_CMANAGER (
		  allvalue string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/import_data/sadata/FIN_CUST_CMANAGER';
