drop table hyperbase_FIN_CUST_INFO_SUB;
CREATE EXTERNAL TABLE hyperbase_FIN_CUST_INFO_SUB (
  rk struct<CUSTNO:STRING>,
  AGEPART STRING,
  DEPOSITBALAVGL3MPART STRING,
  FASSETBALPART STRING
)
ROW FORMAT DELIMITED
COLLECTION ITEMS TERMINATED BY '~'
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES (
"hbase.columns.mapping" = ":key,f1:AGEPART,f1:DEPOSITBALAVGL3MPART,f1:FASSETBALPART"
)TBLPROPERTIES ("hbase.table.name" = "FIN_CUST_INFO_SUB");
