DROP TABLE IF EXISTS sample_FIN_CUST_INFO_SUB;
CREATE EXTERNAL TABLE sample_FIN_CUST_INFO_SUB (
		  allvalue string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/import_data/sadata/FIN_CUST_INFO_SUB';
