SELECT LEA.RECCREATEDATE,
       LEA.rk.CLTID,
       LEA.CUSTNO,
       LEA.LEADOPPPHASE,
       LEA.USERID,
       LEA.ORGID,
       LEA.RECCREATEUID,
       CAM.EXECUTEDATE,
       FM.rk.FEMPID,
       BASE.CUSTNAME,
       BASE.CUSTTYPE,
       BASE.SEX
  FROM          HYPERBASE_FIN_LEADOPPS LEA
             INNER JOIN
                HYPERBASE_FIN_CAMPLEADTEM CAM
             ON CAM.CLTID = LEA.rk.CLTID
          INNER JOIN
             HYPERBASE_FIN_CUST_FMANAGER FM
          ON FM.CUSTNO = LEA.CUSTNO
       INNER JOIN
          HYPERBASE_FIN_CUST_INFO_BASE BASE
       ON BASE.rk.CUSTNO = LEA.CUSTNO
 WHERE FM.rk.FEMPID = '0000000001';
