SELECT SUB.FASSETBALPART AS FASSETBALPART,
       SUM (CON.FASSETBAL) / 10000 AS FASSETBAL,
       SUM (CON.FASSETBALMAX) / 10000 AS FASSETBALMAX,
       SUM (CON.FASSETBALAVGMMAX) / 10000 AS FASSETBALAVGMMAX
  FROM       HYPERBASE_FIN_CONFINPROFILE_BASE CON
          INNER JOIN
             HYPERBASE_FIN_CUST_INFO_SUB SUB
          ON SUB.rk.CUSTNO = CON.rk.CUSTNO
       INNER JOIN
          HYPERBASE_FIN_CUST_ORG ORG
       ON ORG.rk.CUSTNO = CON.rk.CUSTNO
 WHERE ORG.ORGID = 'ORGID4418'
GROUP BY SUB.FASSETBALPART
ORDER BY FASSETBALPART;
